routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WeatherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('user', UserController::class);

    Route::resource('map', MapController::class);

    Route::resource('task', TaskController::class);

    Route::resource('weather', WeatherController::class);

    Route::resource('analytics', AnalyticsController::class);
});

require __DIR__.'/auth.php';

app/Models/Analytics.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Analytics extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use App\Dictionary\UserRole;
use App\Traits\Statusable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, Statusable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role', 'first_name', 'last_name', 'middle_name', 'phone', 'telegram', 'status', 'password'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * @return HasMany
     */
    public function tasks(): HasMany
    {
        return $this->hasMany(Task::class);
    }

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @return string
     */
    public function getRoleNameAttribute(): string
    {
        return UserRole::ROLES[$this->role];
    }
}

app/Http/Controllers/AnalyticsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Analytics;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

class AnalyticsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        return view('analytics.index', [
            'analytics' => Analytics::query()->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return RedirectResponse
     */
    public function create()
    {
        Analytics::factory(10)->create();

        return redirect()->route('analytics.index')->with('success', 'Аналитика Произведена!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/analytics/create.blade.php
@section('title', 'Добавление Показателя')
@section('section', 'Управление Показателями')
@section('breadcrumbs', Breadcrumbs::render('weather.create'))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Добавление</strong> Показателя</h2>
        </header>

        {!! Form::open(['route' => 'weather.store', 'class' => 'form body-tile']) !!}
        @include('weather.form', ['weather' => $weather])
        {!! Form::close() !!}
    </section>
</x-app-layout>

resources/views/analytics/edit.blade.php
@section('title', 'Редактирование Показателя')
@section('section', 'Управление Показателями')
@section('breadcrumbs', Breadcrumbs::render('weather.edit', $weather))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Редактирование</strong> Показателя</h2>
        </header>

        {!! Form::model($weather, ['route' => ['weather.update', $weather->id], 'method' => 'PUT', 'class' => 'form body-tile']) !!}
        @include('weather.form', ['weather' => $weather])
        {!! Form::close() !!}
    </section>
</x-app-layout>

resources/views/analytics/form.blade.php
<div class="row">
    <div class="col form-item">
        {!! Form::label('temperature', 'Температура:') !!}
        {!! Form::text('temperature', null, ['class' => 'inp', 'placeholder' => 'Наименование', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('humidity', 'Влажность:') !!}
        {!! Form::text('humidity', null, ['class' => 'inp', 'placeholder' => 'Куст', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('pressure', 'Давление:') !!}
        {!! Form::text('pressure', null, ['class' => 'inp', 'placeholder' => 'Требования']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('precipitation', 'Осадки:') !!}
        {!! Form::text('precipitation', null, ['class' => 'inp', 'placeholder' => 'Объем', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('wind', 'Ветер:') !!}
        {!! Form::text('wind', null, ['class' => 'inp', 'placeholder' => 'Срок', 'required']) !!}
    </div>
</div>

<footer class="row footer-tile">
    <a href="{{ URL::previous() }}" class="button light-red">Отмена</a>
    <input type="submit" value="Сохранить" class="button success">
</footer>

resources/views/analytics/index.blade.php
@section('title', 'Обзор Аналитики')
@section('section', 'Управление Аналитикой')
@section('breadcrumbs', Breadcrumbs::render('analytics.index'))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Обзор</strong> Аналитики</h2>

            <nav class="controls">
                <a href="{!! route('analytics.create') !!}"><i class="fa fa-plus"></i> Рекомендации</a>
            </nav>
        </header>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Вероятность</th>
                <th>Влажность</th>
                <th>Осадки</th>
                <th>Температура</th>
                <th>Период</th>
                <th>Анализ</th>
                <th>Длительность</th>
            </tr>
            </thead>
            <tbody>
            @forelse($analytics as $analytic)
                <tr>
                    <td>{{ $analytic->id }}.</td>
                    <td>{{ $analytic->name }}</td>
                    <td><a href="#">{{ $analytic->probability }}</a></td>
                    <td>{{ $analytic->humidity }}</td>
                    <td>{{ $analytic->precipitation }}</td>
                    <td>{{ $analytic->temperature }}</td>
                    <td>{{ $analytic->period }}</td>
                    <td><a href="#">{{ $analytic->analysis }}</a></td>
                    <td>{{ $analytic->duration }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9">
                        <div class="message warning" role="alert">Аналитика не найдена!</div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>

        {{ $analytics->links() }}
    </section>
</x-app-layout>

resources/views/analytics/show.blade.php
@section('title', 'Просмотр Операции')
@section('section', 'Управление Операциями')
@section('breadcrumbs', Breadcrumbs::render('map.show', $map))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Просмотр</strong> Операции</h2>
        </header>

        <article class="body-tile form">
            <div class="row">
                <div class="col form-item">
                    <span class="label">Имя:</span>
                    <span class="inp">{{ $map->first_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Фамилия:</span>
                    <span class="inp">{{ $map->last_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Отчество:</span>
                    <span class="inp">{{ $map->middle_name }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Telegram:</span>
                    <span class="inp">{{ $map->telegram }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Телефон:</span>
                    <span class="inp">{{ $map->phone }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Роль:</span>
                    <span class="inp">{{ $map->role_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Статус:</span>
                    <span class="inp">{{ $map->status_text }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Дата Создания:</span>
                    <span class="inp">{{ $map->created_at }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Дата Изменения:</span>
                    <span class="inp">{{ $map->updated_at }}</span>
                </div>
            </div>

            <footer class="row footer-tile">
                <a href="{{ URL::previous() }}" class="button">Назад</a>
            </footer>
        </article>
    </section>
</x-app-layout>