routes/web.php
<?php

use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WeatherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('user', UserController::class);

    Route::resource('map', MapController::class);

    Route::resource('task', TaskController::class);

    Route::resource('weather', WeatherController::class);

    Route::resource('analytics', AnalyticsController::class);
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use App\Dictionary\UserRole;
use App\Traits\Statusable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, Statusable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role', 'first_name', 'last_name', 'middle_name', 'phone', 'telegram', 'status', 'password'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * @return HasMany
     */
    public function tasks(): HasMany
    {
        return $this->hasMany(Task::class);
    }

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @return string
     */
    public function getRoleNameAttribute(): string
    {
        return UserRole::ROLES[$this->role];
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>@yield('title')</title>
    {!! Html::favicon('favicon.ico') !!}
    {!! Html::style('css/reset.css') !!}
    {!! Html::style('css/grid.css') !!}
    {!! Html::style('css/table.css') !!}
    {!! Html::style('css/form.css') !!}
    {!! Html::style('css/drop-down.css') !!}
    {!! Html::style('css/bread-crumb.css') !!}
    {!! Html::style('css/pagination.css') !!}
    {!! Html::style('css/message.css') !!}
    {!! Html::style('css/tooltip.css') !!}
    {!! Html::style('css/other.css') !!}
    {!! Html::style('css/font.css') !!}
    {!! Html::style('css/font-awesome.css') !!}
    {!! Html::style('css/admin.css') !!}
</head>
<body>

<header class="row-layout header-page">
    <div class="col-fixed branding">
        <a href="{{ route('dashboard') }}"><strong>Wine</strong> System</a>
    </div>

    <nav class="pull-right profile-menu drop-down">
        <a href="javascript:void(0)" class="row-layout middle drop-down-toggle">
            {!! Html::image('/images/no_user.jpg', Auth::user()->full_name, ['class' => 'size-30x30 img-circle']) !!}
            <span>{{ Auth::user()->full_name }}</span>
            <i class="fa fa-angle-down"></i>
        </a>
        <ul class="drop-down-menu">
            <li><a href="{!! route('logout') !!}"><i class="fa fa-sign-out"></i> Выход</a></li>
        </ul>
    </nav>
</header>

<aside class="sidebar-left">
    <nav class="main-menu">
        <ul>@include('vendor.menu.admin', ['items' => $adminMenu->roots()])</ul>
    </nav>
</aside>

<article class="content">
    <header class="header-content">
        <h1>@yield('section')</h1>

        <nav class="bread-crumb">
            @yield('breadcrumbs')
        </nav>
    </header>

    @include('vendor.message.default')

    {{ $slot }}
</article>

{!! Html::script('js/jquery.js') !!}
{!! Html::script('js/select.js') !!}
{!! Html::script('js/notifications.js') !!}
{!! Html::script('js/admin.js') !!}
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Login</title>
    {!! Html::favicon('favicon.ico') !!}
    {!! Html::style('css/reset.css') !!}
    {!! Html::style('css/grid.css') !!}
    {!! Html::style('css/font.css') !!}
    {!! Html::style('css/font-awesome.css') !!}
    {!! Html::style('css/message.css') !!}
    {!! Html::style('css/login.css') !!}
</head>
<body>
    {{ $slot }}
</body>
</html>